---
name: ci

on:
  # for feature branches
  pull_request:

jobs:
  ci:
    name: ci
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4.2.2

      - uses: erlef/setup-beam@v1.18.2
        with:
          otp-version: 26
          rebar3-version: 3.24

      - run: make ci
